- name: Create a monitoring namespace
  kubernetes.core.k8s:
    name: monitoring
    api_version: v1
    kind: Namespace
    state: present

- name: Add local Helm chart repository
  kubernetes.core.helm_repository:
    name: helm-local
    binary_path: /usr/local/bin/helm
    repo_url: '{{ monitoring_helm_repository }}'
    state: present

- include_tasks: prometheus-basic.yml
- include_tasks: grafana-dashboards.yml
- include_tasks: grafana.yml
