---

- name: get join command
  delegate_to: '{{ masterNode }}'
  shell: kubeadm token create --print-join-command
  register: join_command  

- name: set join command
  delegate_to: '{{ masterNode }}'
  set_fact:
    join_command: "{{ join_command.stdout_lines[0] | trim }}"  

- name: show join command
  debug: 
    msg : "{{ join_command }}" 

- name: join cluster
  shell: "{{ join_command }} >> node_joined.txt"
  #shell: "{{ join_command }} --ignore-preflight-errors all  >> node_joined.txt"
  args:
    chdir: $HOME
    creates: node_joined.txt    