---
- name: Check if kubernetes already joined cluster
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubernetes_init_status

- name: Join to K8S Cluster
  block:
    - name: get join command
      delegate_to: '{{ masterNode }}'
      shell: kubeadm token create --print-join-command
      register: join_command  

    - name: set join command
      delegate_to: '{{ masterNode }}'
      set_fact:
        join_command: "{{ join_command.stdout_lines[0] | trim }}"  

    - name: show join command
      debug: 
        msg : "{{ join_command }}" 

    - name: join cluster
      shell: "{{ join_command }} --ignore-preflight-errors all  >> node_joined.txt"      
      args:
        chdir: ~/
        creates: node_joined.txt    
  when: not kubernetes_init_status.stat.exists
