---
- name: Add nginx-ingress chart repo
  kubernetes.core.helm_repository:
    name: helm-local
    binary_path: /usr/local/bin/helm
    repo_url: '{{ local_helm_repository }}'
    state: present

- name: Deploy nginx-ingress helm chart
  kubernetes.core.helm:
    name: nginx-ingress
    binary_path: /usr/local/bin/helm
    chart_ref: helm-local/nginx-ingress
    create_namespace: true
    release_namespace: nginx-ingress
    wait: true
    values: 
      controller:        
        image:
          repository: '{{ local_container_repo }}/nginx/nginx-ingress'
          tag: "3.5.0"
        pod:
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/path: /metrics
            prometheus.io/port: "9113" 
            
        config:
          entries: {            
              client-max-body-size: '500m'
          }
      prometheus:       
        create: false        
        port: 9113
        scheme: http

         