---
- name: Install Prerequisites
  hosts: all
  become: true
  roles:
   - role: pre-setup
   - role: swapfile
   - role: selinux
   - role: configure-network
   - role: firewallstate
     firewall_service_state: "disable" # we are using Calico to manage host firewall behaviour
  #  - role: firewallstate
  #    firewall_service_state: "enable"
   - role: crio
   - role: install-k8s
  # - role: groups_and_users
  tags: Prerequisites

- name: Install Master Nodes
  hosts: masters
  become: true
  roles:
  #  - role: configure-firewall
  #    fire_wall_ports: "{{ master_firewall_ports }}"
  - role: master-nodes
  - role: helm-install
  tags: MasterNodes

- name: Install Kubernetes Worker Nodes
  hosts: workers
  become: true
  roles:
  #  - role: configure-firewall
  #    fire_wall_ports: "{{ worker_firewall_ports }}"
  - role: worker-nodes
  tags: WorkerNodes

- name: Configure Calico Firewalls, Storage & Applications
  hosts: masters
  become: true
  roles:
  #- role: calico-firewall
  - role: metallb
  - role: ingress
  - role: nfs-subdir  
  tags: Applications

- name: Monitoring Applications
  hosts: masters
  become: true
  roles:  
  - role: monitoring
  tags: Monitoring
