---
- name: Install Prerequisites
  hosts: all
  become: true
  roles:
   - role: pre-setup
   - role: swapfile
   - role: selinux
   - role: configure-network
   - role: firewall-state
     firewall_state_service_state: "disable" # we are using Calico to manage host firewall behaviour
  #  - role: firewall-state
  #    firewall_state_service_state: "enable"
   - role: configure-crio
   - role: install-k8s
   
  tags: Prerequisites

- name: Install Master Nodes
  hosts: masters
  become: true
  roles:
  #  - role: configure-firewall
  #    configure_firewall_firewall_ports: "{{ master_firewall_ports }}"
   - role: master-nodes
   - role: helm-install
  tags: MasterNodes

- name: Install Kubernetes Worker Nodes
  hosts: workers
  become: true
  roles:
  #  - role: configure-firewall
  #    configure_firewall_firewall_ports: "{{ worker_firewall_ports }}"
   - role: worker-nodes
  tags: WorkerNodes

- name: Configure Calico Firewalls, Storage & Ingress and Load Balancing
  hosts: masters
  become: true
  roles:
   - role: calico-firewall
   - role: metallb
   - role: ingress
   - role: nfs-subdir
   - role: kubernetes-reflector 
  tags: Applications

- name: Pre Applications Items All Hosts
  hosts: all
  become: true
  roles:
   - role: groups_and_users
  tags: PreApplications

- name: Pre Applications Items Master Node
  hosts: masters
  become: true
  roles:
   - role: network_shares
  tags: PreApplications

- name: Monitoring Applications
  hosts: masters
  become: true
  roles:  
   - role: monitoring
  tags: Monitoring


