---
- name: Install Prerequisites
  hosts: all  
  become: yes
  roles:
   - role: pre-setup
   - role: swapfile
   - role: selinux
   - role: configure-network
   - role: firewallstate
     firewall_service_state: "disable" # we are using Calico to manage host firewall behaviour
  #  - role: firewallstate
  #    firewall_service_state: "enable"  
   - role: crio
   - role: install-k8s
  tags: Prerequisites

- name: Install Master Nodes
  hosts: masters
  become: yes
  roles:
  #  - role: configure-firewall
  #    fire_wall_ports: "{{ master_firewall_ports }}"
  - role: master-nodes
  tags: MasterNodes

- name: Install Kubernetes Worker Nodes
  hosts: workers
  become: yes  
  roles:
  #  - role: configure-firewall
  #    fire_wall_ports: "{{ worker_firewall_ports }}"
  - role: worker-nodes
  tags: WorkerNodes

- name: Configure Calico Firewalls & Applications
  hosts: masters
  become: yes
  roles:
  - role: calico-firewall
  - role: metallb
  tags: Applications
