# Groups and Users Used by pods in the cluster
---
- name: Ensure groups exists with correct gid
  ansible.builtin.group:
    name: '{{ item.name }}'
    state: present
    gid: '{{ item.id }}'
  with_items: 
    - '{{ group_and_users_groups }}'

- name: Add the users with a specific uid and a primary group of 'admi
  ansible.builtin.user:
    name:  '{{ item.name }}'
    comment: '{{ item.comment }}'
    uid: '{{ item.id }}'
    group: '{{ item.group }}'
    system: true
    password: '!' 
    state: present
  with_items: 
    - '{{ group_and_users_users }}'    



