---
- name: Add chart repo
  kubernetes.core.helm_repository:
    name: helm-local
    binary_path: /usr/local/bin/helm
    repo_url: '{{ metallb_helm_repository }}'
    state: present

- name: Deploy Metallb helm chart
  kubernetes.core.helm:
    name: metallb
    binary_path: /usr/local/bin/helm
    chart_ref: helm-local/metallb
    create_namespace: true
    release_namespace: metallb-system
    wait: true
    values: 
      controller:
        image:
          repository: '{{ metallb_container_repo }}/metallb/controller'
          tag: v0.13.9
      speaker:
        image:
          repository: '{{ metallb_container_repo }}/metallb/speaker' 
          tag: v0.13.9   

- name: Create Metallb IP Address Range and Advertise
  template: 
    src: metallb-ipaddresses.j2 
    dest: ~/metallb-ipaddresses.yaml

- name: wait for pods to come up
  ansible.builtin.include_tasks:
    file: common/tasks/waitforpods.yaml

# Even though this is here may still need to apply it locally.
- name: Apply Metallb IP Address Range and Advertise (does not always work the first time)
  kubernetes.core.k8s:
    state: present
    src: ~/metallb-ipaddresses.yaml
    wait: no    
  ignore_errors: true
