---
- name: Copy the Metallb Native setup file
  template: 
    src: metallb-native.j2
    dest: ~/metallb-native.yaml 

- name: Apply the Metallb Native setup file
  kubernetes.core.k8s:
    state: present
    src: ~/metallb-native.yaml    
    wait: no
    wait_condition:
      type: Complete
      status: "True"
  ignore_errors: true    

- name: Create Metallb IP Address Range and Advertise
  template: 
    src: metallb-ipaddresses.j2 
    dest: ~/metallb-ipaddresses.yaml

- name: wait for pods to come up
  ansible.builtin.include_tasks:
    file: common/tasks/waitforpods.yaml

- name: Apply Metallb IP Address Range and Advertise (does not always work the first time)
  kubernetes.core.k8s:
    state: present
    src: ~/metallb-ipaddresses.yaml
    wait: no    
  ignore_errors: true
