---
# tasks file for installing and configuring CRIO 

- name: Ensure the helm directory exists
  file:
    path: ~/helm
    state: directory

- name: Install Helm via the tar file mechanism
  ansible.builtin.unarchive:    
    src: helm-v3.11.3-linux-amd64.tar
    dest: ~/helm

- name: Copy Helm tar
  copy:
    remote_src: true
    src: ~/helm/linux-amd64/helm
    dest: /usr/local/bin
    owner: root
    group: root
    mode: 711

- name: Remove the helm directory
  file:
    path: ~/helm
    state: absent
