---
# tasks file for putting SELINUX into permissive mode
- name: Put SELinux in the required mode, logging actions that would be blocked if permissive
  ansible.posix.selinux:
    policy: targeted
    state: permissive  
    #state: enforcing