---

- name: Directory for postgress
  ansible.builtin.file:
    path: "{{ ( network_shares_root_path ,'postgress') | path_join }}"
    state: directory
    recurse: yes
    owner: postgress
    group: postgress      
    mode: 0774

- name: Directory for grafana
  ansible.builtin.file:
    path: "{{ ( network_shares_root_path ,'grafana') | path_join }}"          
    state: directory
    recurse: yes
    owner: grafana
    group: grafana           
    mode: 0774

- name: Directory for prometheus
  ansible.builtin.file:
    path: "{{ ( network_shares_root_path ,'prometheus') | path_join }}"          
    state: directory
    recurse: yes
    owner: grafana
    group: grafana 
    mode: 0774