---
# tasks file for installing and configuring kubernetes 
- name: Copy RPM-GPG-KEY-google GPG public key
  ansible.builtin.copy:
    src: RPM-GPG-KEY-google
    dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-google

- name: Add Google YUM repository
  yum_repository:
    name: Google
    description: Google YUM repository
    baseurl: '{{ kubernetes_yum_repo }}'
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-google
    gpgcheck: yes
    repo_gpgcheck: 1
    enabled: 1

- name: Install kubernetes packages
  yum:
    name: [kubelet-1.27.1-0,kubeadm-1.27.1-0,kubectl-1.27.1-0]
    disable_excludes: kubernetes
    state: present

- name: Enable kubelet service
  ansible.builtin.service:
    name: kubelet
    enabled: yes    
