---
# tasks file for installing and configuring kubernetes 
- name: Copy RPM-GPG-KEY-kubernetes GPG public key
  ansible.builtin.copy:
    src: RPM-GPG-KEY-kubernetes
    dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-kubernetes

- name: Add Kubernetes YUM repository
  yum_repository:
    name: 'Kubernetes{{item.0}}'
    file: 'Kubernetes'
    description: Kubernetes YUM repository
    baseurl: '{{ item.1 }}'
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-kubernetes
    gpgcheck: true
    repo_gpgcheck: false
    enabled: true
  with_indexed_items:  '{{ install_k8s_kubernetes_yum_repos }}' 
    
- name: Install kubernetes packages
  yum:
    name: ['kubelet-{{ install_k8s_kubernetesVersion }}','kubeadm-{{ install_k8s_kubernetesVersion }}','kubectl-{{ install_k8s_kubernetesVersion }}']
    disable_excludes: kubernetes
    state: present

- name: Enable kubelet service
  ansible.builtin.service:
    name: kubelet
    enabled: yes    
