---
# tasks file for configuring firewall ports

- name: Configure firewalld firewall ports
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  with_items: '{{ configure_firewall_firewall_ports }}'

- name: Reload firewalld
  shell: firewall-cmd --reload  