---
# tasks file for installing and configuring CRIO 

- name: Setup Yum Repo  /etc/yum.repos.d/devel:kubic:libcontainers:stable.repo 
  command: curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable.repo https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{calicoOS}}/devel:kubic:libcontainers:stable.repo

- name: Setup Yum Repo /etc/yum.repos.d/devel:kubic:libcontainers:stable:cri-o:VERSION.repo
  command: curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable:cri-o:{{calicoVersion}}.repo https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/{{calicoVersion}}/{{calicoOS}}/devel:kubic:libcontainers:stable:cri-o:{{calicoVersion}}.repo

- name: Install cri-o
  yum:
    name: cri-o
    state: present
    update_cache: yes

- name: Configure cri-o subnet
  ansible.builtin.replace:
    path: /etc/cni/net.d/100-crio-bridge.conf
    regexp: '10\.85\.0\.0\/16'
    replace: '{{ pod_network_cidr }}'
  ignore_errors: True                              

- name: Start and enable crio service
  ansible.builtin.service:
    name: crio
    state: restarted
    enabled: yes
