---
# tasks file for installing and configuring CRIO 

- name: Copy RPM-GPG-KEY-opensuse GPG public key
  ansible.builtin.copy:
    src: RPM-GPG-KEY-opensuse
    dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-opensuse

- name: Add Opensuse YUM repository
  yum_repository:
    name: opensuse
    description: opensuse YUM repository
    baseurl: '{{ opensuse_yum_repo }}'
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-opensuse
    gpgcheck: yes
    repo_gpgcheck: 1
    enabled: 1

- name: Install cri-o
  yum:
    name: cri-o
    state: present
    update_cache: yes

- name: Configure cri-o subnet
  ansible.builtin.replace:
    path: /etc/cni/net.d/100-crio-bridge.conflist
    regexp: '10\.85\.0\.0\/16'
    replace: '{{ pod_network_cidr }}'
  ignore_errors: True                              

- name: Start and enable crio service
  ansible.builtin.service:
    name: crio
    state: restarted
    enabled: yes
